spring.application.name=02_MANY_TO_ONE



spring.datasource.username=root
spring.datasource.password=eshwar
spring.datasource.url=jdbc:mysql://localhost:3306/association_mapping


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update